version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: hiring_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  nestjs-app:
    build: .
    ports:
      - "8082:8082" #cổng chính
      - "8080:8080" #cổng cho websocket
    env_file:                
      - .env
    depends_on:
      - mongodb
    networks:
      - app-network

volumes:
  mongodb_data:
    external: false

networks:
  app-network:
    driver: bridge
