apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb  # Đảm bảo label này trùng với label trong pod MongoDB
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
